In [52]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [53]:
brands=pd.read_csv("brands.csv",index_col=0)

In [54]:
brands.head(50)

id                       name
0   30                AM/NS (CRC)
1   11              AM/NS (Essar)
2   32                  AM/NS(CC)
3    9                     Apollo
4   33             Apollo GP Pipe
5   14              As Per IS2062
6   58                 EN8 Series
7    5               G.D.MALHOTRA
8   23                JINDAL STAR
9   24        Jindal Steel (JSPL)
10  13              JSW Colouron+
11  53              JSW Decksheet
12  60               JSW GP Sheet
13  36           JSW Kalinga Pipe
14  35  JSW Kalinga Z Fab GP Pipe
15  61                JSW Pragati
16  45                    JSW TMT
17   3              Mahavir Steel
18  21               MSL Seamless
19  46                      Other
20  40                    PC Lite
21  38              Pipe Fittings
22  16                 Polish Bar
23  29                     Primus
24   8                 Rajuri TMT
25  15                    Rolling
26  59                       SAIL
27  51                       TATA
28  27             TATA Durashine
29  47                TATA EZYFIT
30  62               TATA GI PIPE
31  25              TATA GP Pipe 
32  57                    TATA HR
33  17                 TATA Pipes
34  54             TATA SMARTDEK 
35   1             TATA Structura
36  50                TATA TISCON
37   7               VIZAG / SAIL

In [55]:
sorted(brands["id"].unique())

[1,
 3,
 5,
 7,
 8,
 9,
 11,
 13,
 14,
 15,
 16,
 17,
 21,
 23,
 24,
 25,
 27,
 29,
 30,
 32,
 33,
 35,
 36,
 38,
 40,
 45,
 46,
 47,
 50,
 51,
 53,
 54,
 57,
 58,
 59,
 60,
 61,
 62]

In [56]:
brands["name"].unique()

array(['AM/NS (CRC)', 'AM/NS (Essar)', 'AM/NS(CC)', 'Apollo',
       'Apollo GP Pipe', 'As Per IS2062', 'EN8 Series', 'G.D.MALHOTRA',
       'JINDAL STAR', 'Jindal Steel (JSPL)', 'JSW Colouron+',
       'JSW Decksheet', 'JSW GP Sheet', 'JSW Kalinga Pipe',
       'JSW Kalinga Z Fab GP Pipe', 'JSW Pragati', 'JSW TMT',
       'Mahavir Steel', 'MSL Seamless', 'Other', 'PC Lite',
       'Pipe Fittings', 'Polish Bar', 'Primus', 'Rajuri TMT', 'Rolling',
       'SAIL', 'TATA', 'TATA Durashine', 'TATA EZYFIT', 'TATA GI PIPE',
       'TATA GP Pipe ', 'TATA HR', 'TATA Pipes', 'TATA SMARTDEK ',
       'TATA Structura', 'TATA TISCON', 'VIZAG / SAIL'], dtype=object)

In [57]:
brands.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38 entries, 0 to 37
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      38 non-null     int64 
 1   name    38 non-null     object
dtypes: int64(1), object(1)
memory usage: 912.0+ bytes


In [58]:
brands[brands.duplicated()]

Empty DataFrame
Columns: [id, name]
Index: []

In [59]:
brands.isnull().values.any()


False

In [60]:
brands.isnull().sum()

id      0
name    0
dtype: int64

In [61]:
products=pd.read_csv("products.csv",index_col=0)

In [62]:
products.head(50)

month  year  brandid  pwid       brandname        productname  \
0       8  2020        3   167   Mahavir Steel              Angle   
1       8  2020       17     1      TATA Pipes     G.I. Pipe(Mtr)   
2       8  2020        5   403    G.D.MALHOTRA               Beam   
3       8  2020        3   226   Mahavir Steel            Channel   
4       8  2020       16   526      Polish Bar         Polish Bar   
5       8  2020       17   106      TATA Pipes  Round_Pipes (Mtr)   
6       8  2020        8   239      Rajuri TMT                TMT   
7       8  2020        7   234    VIZAG / SAIL            Channel   
8       8  2020       11   514   AM/NS (Essar)             SHEET    
9       8  2020        5   223    G.D.MALHOTRA            Channel   
10      8  2020        1    20  TATA Structura        Square_Pipe   
11      8  2020       17   558      TATA Pipes  Round_Pipes (Mtr)   
12      8  2020        7   228    VIZAG / SAIL            Channel   
13      8  2020        7   231    VIZAG / SAIL            Channel   
14      8  2020        7   206    VIZAG / SAIL              Angle   
15      8  2020        7   410    VIZAG / SAIL               Beam   
16      8  2020       11   467   AM/NS (Essar)              Plate   
17      8  2020        3   341   Mahavir Steel               Flat   
18      8  2020        1    27  TATA Structura        Square_Pipe   
19      8  2020       15   385         Rolling          Round_Bar   
20      8  2020       15   254         Rolling               Flat   
21      8  2020        1   145  TATA Structura        Square_Pipe   
22      8  2020        1   146  TATA Structura        Square_Pipe   
23      8  2020        1   343  TATA Structura        Square_Pipe   
24      8  2020       15   255         Rolling               Flat   
25      8  2020       14   328   As Per IS2062               Flat   
26      8  2020       11   463   AM/NS (Essar)              Plate   
27      8  2020       11   444   AM/NS (Essar)              Plate   
28      8  2020       11   501   AM/NS (Essar)             SHEET    
29      8  2020        5   226    G.D.MALHOTRA            Channel   
30      8  2020       15   371         Rolling         Square_Bar   
31      8  2020       14   304   As Per IS2062               Flat   
32      8  2020       11   507   AM/NS (Essar)             SHEET    
33      8  2020        5   179    G.D.MALHOTRA              Angle   
34      8  2020        1    63  TATA Structura        Square_Pipe   
35      8  2020       11   436   AM/NS (Essar)              Plate   
36      8  2020       14   282   As Per IS2062               Flat   
37      8  2020       11   432   AM/NS (Essar)              Plate   
38      8  2020        5   267    G.D.MALHOTRA               Flat   
39      8  2020        5   261    G.D.MALHOTRA               Flat   
40      8  2020       14   269   As Per IS2062               Flat   
41      8  2020       11   476   AM/NS (Essar)              Plate   
42      8  2020       11   435   AM/NS (Essar)              Plate   
43      8  2020       11   433   AM/NS (Essar)              Plate   
44      8  2020       11   455   AM/NS (Essar)              Plate   
45      8  2020       11   446   AM/NS (Essar)              Plate   
46      8  2020        5   229    G.D.MALHOTRA            Channel   
47      8  2020        5   225    G.D.MALHOTRA            Channel   
48      8  2020        3   342   Mahavir Steel               Flat   
49      8  2020        5   296    G.D.MALHOTRA               Flat   

                 name   weight  
0           25*25*3mm     11.0  
1     100_5.4_C Class   1480.0  
2            100*50 L   1707.3  
3          75*40 -1.7     34.2  
4              R 16mm      9.5  
5   150_C CLASS_5.4mm   5836.2  
6               06 MM    195.7  
7          200*75 STD   8909.3  
8       3mm*1020*3050    146.0  
9               70*35   4160.0  
10   25*25*1.6_YST210   2937.2  
11  125_C CLASS_5.4mm   3329.4  
12         100*50 STD  45582.9  
13         125*65 STD 

In [63]:
products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18881 entries, 0 to 18880
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   month        18881 non-null  int64  
 1   year         18881 non-null  int64  
 2   brandid      18881 non-null  int64  
 3   pwid         18881 non-null  int64  
 4   brandname    18881 non-null  object 
 5   productname  18881 non-null  object 
 6   name         18881 non-null  object 
 7   weight       18881 non-null  float64
dtypes: float64(1), int64(4), object(3)
memory usage: 1.3+ MB


In [64]:
products[products.duplicated()]

Empty DataFrame
Columns: [month, year, brandid, pwid, brandname, productname, name, weight]
Index: []

In [65]:
products.isnull().values.any()

False

In [66]:
products.isnull().sum()


month          0
year           0
brandid        0
pwid           0
brandname      0
productname    0
name           0
weight         0
dtype: int64

In [67]:
products["month"].unique()

array([ 8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7], dtype=int64)

In [68]:
products["year"].unique()

array([2020, 2021, 2022, 2023, 2024, 2025], dtype=int64)

In [69]:
products["brandid"].unique()

array([ 3, 17,  5, 16,  8,  7, 11,  1, 15, 14,  9, 13, 24, 21, 27, 25, 23,
       30, 33, 32, 35, 38, 40, 36, 45, 47, 46, 51, 59, 29, 60, 61, 58, 50],
      dtype=int64)

In [70]:
products["pwid"].unique()

array([ 167,    1,  403, ..., 1438, 1227, 1458], dtype=int64)

In [71]:
df = products.merge(brands, left_on='brandid', right_on='id', how='left')



In [72]:
df

month  year  brandid  pwid       brandname     productname  \
0          8  2020        3   167   Mahavir Steel           Angle   
1          8  2020       17     1      TATA Pipes  G.I. Pipe(Mtr)   
2          8  2020        5   403    G.D.MALHOTRA            Beam   
3          8  2020        3   226   Mahavir Steel         Channel   
4          8  2020       16   526      Polish Bar      Polish Bar   
...      ...   ...      ...   ...             ...             ...   
18876      1  2025       15   180         Rolling           Angle   
18877      1  2025       17   662      TATA Pipes     Round_Pipes   
18878      1  2025        1   359  TATA Structura     Square_Pipe   
18879      1  2025        1   113  TATA Structura     Round_Pipes   
18880      1  2025        1   145  TATA Structura     Square_Pipe   

                 name_x  weight  id          name_y  
0             25*25*3mm    11.0   3   Mahavir Steel  
1       100_5.4_C Class  1480.0  17      TATA Pipes  
2              100*50 L  1707.3   5    G.D.MALHOTRA  
3            75*40 -1.7    34.2   3   Mahavir Steel  
4                R 16mm     9.5  16      Polish Bar  
...                 ...     ...  ..             ...  
18876         40*40*6mm   525.0  15         Rolling  
18877  40_C CLASS_4.0mm  4000.0  17      TATA Pipes  
18878  72*72*2.6_YST210  4000.0   1  TATA Structura  
18879          20_2.0mm   369.0   1  TATA Structura  
18880  20*20*1.2_YST210   225.0   1  TATA Structura  

[18881 rows x 10 columns]

In [73]:
df.drop(["id"], axis=1, inplace=True)


In [74]:
df

month  year  brandid  pwid       brandname     productname  \
0          8  2020        3   167   Mahavir Steel           Angle   
1          8  2020       17     1      TATA Pipes  G.I. Pipe(Mtr)   
2          8  2020        5   403    G.D.MALHOTRA            Beam   
3          8  2020        3   226   Mahavir Steel         Channel   
4          8  2020       16   526      Polish Bar      Polish Bar   
...      ...   ...      ...   ...             ...             ...   
18876      1  2025       15   180         Rolling           Angle   
18877      1  2025       17   662      TATA Pipes     Round_Pipes   
18878      1  2025        1   359  TATA Structura     Square_Pipe   
18879      1  2025        1   113  TATA Structura     Round_Pipes   
18880      1  2025        1   145  TATA Structura     Square_Pipe   

                 name_x  weight          name_y  
0             25*25*3mm    11.0   Mahavir Steel  
1       100_5.4_C Class  1480.0      TATA Pipes  
2              100*50 L  1707.3    G.D.MALHOTRA  
3            75*40 -1.7    34.2   Mahavir Steel  
4                R 16mm     9.5      Polish Bar  
...                 ...     ...             ...  
18876         40*40*6mm   525.0         Rolling  
18877  40_C CLASS_4.0mm  4000.0      TATA Pipes  
18878  72*72*2.6_YST210  4000.0  TATA Structura  
18879          20_2.0mm   369.0  TATA Structura  
18880  20*20*1.2_YST210   225.0  TATA Structura  

[18881 rows x 9 columns]

In [75]:
df.columns

Index(['month', 'year', 'brandid', 'pwid', 'brandname', 'productname',
       'name_x', 'weight', 'name_y'],
      dtype='object')

In [76]:
df.drop(["name_y"], axis=1, inplace=True)


In [77]:
df

month  year  brandid  pwid       brandname     productname  \
0          8  2020        3   167   Mahavir Steel           Angle   
1          8  2020       17     1      TATA Pipes  G.I. Pipe(Mtr)   
2          8  2020        5   403    G.D.MALHOTRA            Beam   
3          8  2020        3   226   Mahavir Steel         Channel   
4          8  2020       16   526      Polish Bar      Polish Bar   
...      ...   ...      ...   ...             ...             ...   
18876      1  2025       15   180         Rolling           Angle   
18877      1  2025       17   662      TATA Pipes     Round_Pipes   
18878      1  2025        1   359  TATA Structura     Square_Pipe   
18879      1  2025        1   113  TATA Structura     Round_Pipes   
18880      1  2025        1   145  TATA Structura     Square_Pipe   

                 name_x  weight  
0             25*25*3mm    11.0  
1       100_5.4_C Class  1480.0  
2              100*50 L  1707.3  
3            75*40 -1.7    34.2  
4                R 16mm     9.5  
...                 ...     ...  
18876         40*40*6mm   525.0  
18877  40_C CLASS_4.0mm  4000.0  
18878  72*72*2.6_YST210  4000.0  
18879          20_2.0mm   369.0  
18880  20*20*1.2_YST210   225.0  

[18881 rows x 8 columns]

In [78]:
df.rename(columns={'name_x': 'name'}, inplace=True)


In [79]:
df

month  year  brandid  pwid       brandname     productname  \
0          8  2020        3   167   Mahavir Steel           Angle   
1          8  2020       17     1      TATA Pipes  G.I. Pipe(Mtr)   
2          8  2020        5   403    G.D.MALHOTRA            Beam   
3          8  2020        3   226   Mahavir Steel         Channel   
4          8  2020       16   526      Polish Bar      Polish Bar   
...      ...   ...      ...   ...             ...             ...   
18876      1  2025       15   180         Rolling           Angle   
18877      1  2025       17   662      TATA Pipes     Round_Pipes   
18878      1  2025        1   359  TATA Structura     Square_Pipe   
18879      1  2025        1   113  TATA Structura     Round_Pipes   
18880      1  2025        1   145  TATA Structura     Square_Pipe   

                   name  weight  
0             25*25*3mm    11.0  
1       100_5.4_C Class  1480.0  
2              100*50 L  1707.3  
3            75*40 -1.7    34.2  
4                R 16mm     9.5  
...                 ...     ...  
18876         40*40*6mm   525.0  
18877  40_C CLASS_4.0mm  4000.0  
18878  72*72*2.6_YST210  4000.0  
18879          20_2.0mm   369.0  
18880  20*20*1.2_YST210   225.0  

[18881 rows x 8 columns]

In [80]:
df.to_csv('cleaned_data.csv', index=False)
